### ISSUE TITLE
сер катун майнкрафт зависает в последний стадии помоги решить

### ISSUE THREAD

**Issue by hitman228228** [PlutoSolutions/KonasRewrite#12]

**Comment by hitman228228** [comment]
лол

**Comment by mr-nv** [comment]
добавь -noverify

**Comment by mr-nv** [comment]
сука я сообщение сделал при первом запуске вы читать не умеете чтоли бля????

**Comment by u3o** [comment]
какой тебе еще катун

**Comment by hitman228228** [comment]
Дело в том что ему похуй есть новерефи ли нету 
(Я знаю как ставить)

**Comment by hitman228228** [comment]
И игра в помледеий момеет зависает 7стадия

**Comment by hitman228228** [comment]
И ошибку глянуть я не могу поэтому и спрашиваю

**Comment by mr-nv** [comment]
хуй знает впервые вижу чтоб так было
моды другие убери если есть, фордж обнови или джаву, не знаю
но может быть тебе вообще этот хак не нужен...

сб, 6 нояб. 2021 г., 10:20 nedohacker ***@***.***>:

**Comment by mr-nv** [comment]
если у тебя тлаунчер можешь попробовать другой какой нибудь

сб, 6 нояб. 2021 г., 10:20 nedohacker ***@***.***>:

**Comment by hitman228228** [comment]
Мне прост интересно что добавили эти дауны
