### ISSUE TITLE
konas crashing when configured

### ISSUE THREAD

**Issue by OptfineTL** [PlutoSolutions/KonasRewrite#21]
konas crashes when i configure it and close it then open it it crashes try for your self i left my config file down below
[konas.zip](https://github.com/PlutoSolutions/KonasRewrite/files/7933415/konas.zip)

**Comment by mr-nv** [comment]
![image](https://user-images.githubusercontent.com/31269663/151768126-98a3d52b-01ea-454d-9da5-9bcde1a31838.png)
your modules.json file is empty
