### ISSUE TITLE
Konas Not Opening

### ISSUE THREAD

**Issue by CrystalPvpFan** [PlutoSolutions/KonasRewrite#8]
When you load mc it says finished loading but wont show start page

**Comment by CrystalPvpFan** [comment]
just crashed

**Comment by mr-nv** [comment]
remove all other mods and try again
also whats the crash log

**Comment by CrystalPvpFan** [comment]
nvm fixed it after putting -noverify i only had konas and optifine

**Comment by mr-nv** [comment]
whats the crash log still

**Comment by fuckyouthinkimboogieman** [comment]
konas is a shit hack its not possibl;e to use konas with some versions of optifine
